components {
  id: "bucket"
  component: "/assets/go/bucket/bucket.script"
}
embedded_components {
  id: "sprite_back"
  type: "sprite"
  data: "default_animation: \"bucket_back\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/go/bucket/bucket.atlas.atlas\"\n"
  "}\n"
  ""
  position {
    z: -0.5
  }
}
embedded_components {
  id: "sprite_front"
  type: "sprite"
  data: "default_animation: \"bucket_front\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 173.0\n"
  "  y: 208.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/go/bucket/bucket.atlas.atlas\"\n"
  "}\n"
  ""
  position {
    z: 0.8
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "mask: \"marble\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: -82.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -60.0\n"
  "      y: -29.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.6304475\n"
  "      w: 0.7762319\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 64.0\n"
  "      y: -23.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.63044554\n"
  "      w: 0.7762335\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  data: 53.43732\n"
  "  data: 5.2267375\n"
  "  data: 9.84\n"
  "  data: 55.13565\n"
  "  data: 3.623336\n"
  "  data: 9.84\n"
  "  data: 62.83761\n"
  "  data: 3.623336\n"
  "  data: 9.84\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject1"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"complete\"\n"
  "mask: \"default\"\n"
  "mask: \"marble\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 2.0\n"
  "      y: -65.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 47.071793\n"
  "  data: 10.0\n"
  "  data: 10.0\n"
  "}\n"
  "event_collision: false\n"
  "event_contact: false\n"
  ""
}
