components {
  id: "broom"
  component: "/assets/go/broom/broom.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"broom\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/go/broom/broom.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "mask: \"marble\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 6.0\n"
  "      y: 27.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.09966533\n"
  "      w: 0.99502105\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 24.0\n"
  "      y: -60.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.053375877\n"
  "      w: 0.9985745\n"
  "    }\n"
  "    index: 3\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 32.0\n"
  "      y: -107.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.07511923\n"
  "      w: 0.99717456\n"
  "    }\n"
  "    index: 4\n"
  "    count: 3\n"
  "  }\n"
  "  data: 10.0\n"
  "  data: 129.45692\n"
  "  data: 10.0\n"
  "  data: 26.39168\n"
  "  data: 30.312988\n"
  "  data: 41.55907\n"
  "  data: 9.52\n"
  "}\n"
  "event_trigger: false\n"
  ""
}
